import {
  Armchair,
  ArrowLeftRight,
  Banknote,
  BedDouble,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  Cable,
  Cake,
  Car,
  Clapperboard,
  ClipboardPlus,
  CircleDollarSign,
  CircleEllipsis,
  CircleHelp,
  Code,
  Coffee,
  Cookie,
  CreditCard,
  GlassWater,
  Dumbbell,
  FileText,
  Fish,
  Flame,
  FlaskConical,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandHeart,
  Heart,
  HeartPulse,
  House,
  Laptop,
  Mail,
  Milestone,
  MonitorPlay,
  MountainSnow,
  Package,
  PackageOpen,
  Palette,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  PenLine,
  PersonStanding,
  PiggyBank,
  Pill,
  Plane,
  RefreshCcw,
  Sandwich,
  Scissors,
  Send,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Stethoscope,
  Store,
  Tablet,
  Tag,
  Thermometer,
  Ticket,
  TrainFront,
  Trash2,
  TrendingUp,
  Trophy,
  Tv,
  UtensilsCrossed,
  UserRound,
  Users,
  Watch,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideProps,
} from 'lucide-react';
import React from 'react';

type LucideComponent = React.FC<LucideProps>;

const ICON_MAP: Record<string, LucideComponent> = {
  Armchair,
  ArrowLeftRight,
  Banknote,
  BedDouble,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  Cable,
  Cake,
  Car,
  Clapperboard,
  ClipboardPlus,
  CircleDollarSign,
  CircleEllipsis,
  CircleHelp,
  Code,
  Coffee,
  Cookie,
  CreditCard,
  GlassWater,
  Dumbbell,
  FileText,
  Fish,
  Flame,
  FlaskConical,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandHeart,
  Heart,
  HeartPulse,
  House,
  Laptop,
  Mail,
  Milestone,
  MonitorPlay,
  MountainSnow,
  Package,
  PackageOpen,
  Palette,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  PenLine,
  PersonStanding,
  PiggyBank,
  Pill,
  Plane,
  RefreshCcw,
  Sandwich,
  Scissors,
  Send,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Stethoscope,
  Store,
  Tablet,
  Tag,
  Thermometer,
  Ticket,
  TrainFront,
  Trash2,
  TrendingUp,
  Trophy,
  Tv,
  UtensilsCrossed,
  UserRound,
  Users,
  Watch,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
};

/** All Lucide icon names available in this app */
export const ALL_ICON_NAMES = Object.keys(ICON_MAP).sort();

interface CategoryIconProps {
  name: string | null | undefined;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

/** Renders a Lucide icon by string name. Falls back to CircleEllipsis if unknown. */
export default function CategoryIcon({ name, size = 16, color, strokeWidth = 1.75 }: CategoryIconProps) {
  const Icon = (name && ICON_MAP[name]) ? ICON_MAP[name] : CircleEllipsis;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} />;
}
