# Default category and subcategory data — sourced from docs/default_category.md
# Used by category_service.seed_categories() to populate a new ledger's categories.
# icon values are Lucide icon name strings (https://lucide.dev/icons/).
# subcategories is a list of {"name": str, "icon": str} dicts.

CATEGORY_DATA: list[dict] = [
    {
        "name": "Food",
        "transaction_type": "expense",
        "icon": "UtensilsCrossed",
        "subcategories": [
            {"name": "Restaurant", "icon": "UtensilsCrossed"},
            {"name": "Takeout / Delivery", "icon": "PackageOpen"},
            {"name": "Fast Food", "icon": "Sandwich"},
            {"name": "Work Meal", "icon": "BriefcaseBusiness"},
        ],
    },
    {
        "name": "Snack",
        "transaction_type": "expense",
        "icon": "Cookie",
        "subcategories": [
            {"name": "Coffee / Tea", "icon": "Coffee"},
            {"name": "Boba Tea", "icon": "GlassWater"},
            {"name": "Vending Machine", "icon": "ShoppingCart"},
            {"name": "Convenience Store", "icon": "Store"},
            {"name": "Other Snack", "icon": "Cookie"},
        ],
    },
    {
        "name": "Groceries",
        "transaction_type": "expense",
        "icon": "ShoppingCart",
        "subcategories": [
            {"name": "Walmart", "icon": "Store"},
            {"name": "T&T Supermarket", "icon": "Store"},
            {"name": "Superstore", "icon": "Store"},
            {"name": "Alcohol", "icon": "Wine"},
            {"name": "Household Groceries", "icon": "ShoppingBasket"},
        ],
    },
    {
        "name": "Shopping",
        "transaction_type": "expense",
        "icon": "ShoppingBag",
        "subcategories": [
            {"name": "Clothes", "icon": "Shirt"},
            {"name": "Shoes", "icon": "Footprints"},
            {"name": "Accessories", "icon": "Watch"},
            {"name": "Daily Supplies", "icon": "Package"},
            {"name": "Misc Shopping", "icon": "ShoppingBag"},
            {"name": "Dollarama", "icon": "Tag"},
        ],
    },
    {
        "name": "Transportation",
        "transaction_type": "expense",
        "icon": "Bus",
        "subcategories": [
            {"name": "Public Transit", "icon": "Bus"},
            {"name": "Taxi / Uber", "icon": "Car"},
            {"name": "Bike / Scooter", "icon": "Bike"},
            {"name": "Parking", "icon": "ParkingCircle"},
            {"name": "Train / Bus", "icon": "TrainFront"},
        ],
    },
    {
        "name": "Car",
        "transaction_type": "expense",
        "icon": "Car",
        "subcategories": [
            {"name": "Fuel", "icon": "Fuel"},
            {"name": "Insurance", "icon": "Shield"},
            {"name": "Maintenance", "icon": "Wrench"},
            {"name": "Car Wash", "icon": "Droplets"},
            {"name": "Parking", "icon": "ParkingCircle"},
            {"name": "Tolls", "icon": "Milestone"},
        ],
    },
    {
        "name": "Travel",
        "transaction_type": "expense",
        "icon": "Plane",
        "subcategories": [
            {"name": "Flights", "icon": "Plane"},
            {"name": "Hotels", "icon": "BedDouble"},
            {"name": "Local Transport", "icon": "Car"},
            {"name": "Attractions", "icon": "Ticket"},
            {"name": "Travel Food", "icon": "UtensilsCrossed"},
        ],
    },
    {
        "name": "Housing",
        "transaction_type": "expense",
        "icon": "House",
        "subcategories": [
            {"name": "Rent", "icon": "House"},
            {"name": "Mortgage", "icon": "Building"},
            {"name": "Property Tax", "icon": "FileText"},
            {"name": "Condo / HOA Fee", "icon": "Building2"},
            {"name": "Home Repair", "icon": "Hammer"},
            {"name": "Furniture", "icon": "Armchair"},
        ],
    },
    {
        "name": "Utilities",
        "transaction_type": "expense",
        "icon": "Zap",
        "subcategories": [
            {"name": "Electricity", "icon": "Zap"},
            {"name": "Water", "icon": "Droplets"},
            {"name": "Gas", "icon": "Flame"},
            {"name": "Trash", "icon": "Trash2"},
            {"name": "Heating", "icon": "Thermometer"},
            {"name": "Internet", "icon": "Wifi"},
        ],
    },
    {
        "name": "Phone & Internet",
        "transaction_type": "expense",
        "icon": "Smartphone",
        "subcategories": [
            {"name": "Mobile Plan", "icon": "Smartphone"},
            {"name": "Internet", "icon": "Wifi"},
            {"name": "Phone Accessories", "icon": "Cable"},
            {"name": "Subscription", "icon": "RefreshCcw"},
        ],
    },
    {
        "name": "Health",
        "transaction_type": "expense",
        "icon": "HeartPulse",
        "subcategories": [
            {"name": "Pharmacy OTC", "icon": "Pill"},
            {"name": "Prescription", "icon": "ClipboardPlus"},
            {"name": "Doctor Visit", "icon": "Stethoscope"},
            {"name": "Dental", "icon": "Smile"},
            {"name": "Health Insurance", "icon": "HeartPulse"},
            {"name": "Supplements", "icon": "FlaskConical"},
        ],
    },
    {
        "name": "Personal Care",
        "transaction_type": "expense",
        "icon": "Sparkles",
        "subcategories": [
            {"name": "Haircut", "icon": "Scissors"},
            {"name": "Skincare", "icon": "Sparkles"},
            {"name": "Cosmetics", "icon": "Palette"},
            {"name": "Salon", "icon": "Scissors"},
            {"name": "Spa / Massage", "icon": "Waves"},
        ],
    },
    {
        "name": "Entertainment",
        "transaction_type": "expense",
        "icon": "Clapperboard",
        "subcategories": [
            {"name": "Movies", "icon": "Clapperboard"},
            {"name": "Games", "icon": "Gamepad2"},
            {"name": "Streaming Services", "icon": "Tv"},
            {"name": "Events", "icon": "Ticket"},
            {"name": "Hobbies", "icon": "Palette"},
        ],
    },
    {
        "name": "Education",
        "transaction_type": "expense",
        "icon": "GraduationCap",
        "subcategories": [
            {"name": "Tuition", "icon": "GraduationCap"},
            {"name": "Books", "icon": "BookOpen"},
            {"name": "Online Courses", "icon": "MonitorPlay"},
            {"name": "School Supplies", "icon": "PenLine"},
        ],
    },
    {
        "name": "Pet",
        "transaction_type": "expense",
        "icon": "PawPrint",
        "subcategories": [
            {"name": "Pet Food", "icon": "Fish"},
            {"name": "Vet", "icon": "Stethoscope"},
            {"name": "Pet Supplies", "icon": "PawPrint"},
            {"name": "Grooming", "icon": "Scissors"},
            {"name": "Pet Services", "icon": "PawPrint"},
        ],
    },
    {
        "name": "Electronics",
        "transaction_type": "expense",
        "icon": "Laptop",
        "subcategories": [
            {"name": "Computer", "icon": "Laptop"},
            {"name": "Phone", "icon": "Smartphone"},
            {"name": "Tablet", "icon": "Tablet"},
            {"name": "Accessories", "icon": "Cable"},
            {"name": "Software", "icon": "Code"},
        ],
    },
    {
        "name": "Sports",
        "transaction_type": "expense",
        "icon": "Dumbbell",
        "subcategories": [
            {"name": "Gym", "icon": "Dumbbell"},
            {"name": "Sports Equipment", "icon": "Trophy"},
            {"name": "Sports Classes", "icon": "PersonStanding"},
            {"name": "Outdoor Activities", "icon": "MountainSnow"},
        ],
    },
    {
        "name": "Gifts & Donations",
        "transaction_type": "expense",
        "icon": "Gift",
        "subcategories": [
            {"name": "Birthday Gift", "icon": "Cake"},
            {"name": "Holiday Gift", "icon": "Gift"},
            {"name": "Donation", "icon": "Heart"},
            {"name": "Charity", "icon": "HandHeart"},
        ],
    },
    {
        "name": "Red Envelope",
        "transaction_type": "expense",
        "icon": "Mail",
        "subcategories": [
            {"name": "Family", "icon": "Users"},
            {"name": "Friends", "icon": "UserRound"},
            {"name": "Holiday", "icon": "PartyPopper"},
            {"name": "Other", "icon": "Mail"},
        ],
    },
    {
        "name": "Other",
        "transaction_type": "expense",
        "icon": "CircleEllipsis",
        "subcategories": [
            {"name": "Uncategorized", "icon": "CircleHelp"},
            {"name": "Unknown", "icon": "CircleHelp"},
        ],
    },
    {
        "name": "Transfers",
        "transaction_type": "transfer",
        "icon": "ArrowLeftRight",
        "subcategories": [
            {"name": "Credit Card Payment", "icon": "CreditCard"},
            {"name": "Savings Transfer", "icon": "PiggyBank"},
            {"name": "Investment Transfer", "icon": "TrendingUp"},
            {"name": "Cash Withdrawal", "icon": "Banknote"},
            {"name": "Internal Transfer", "icon": "ArrowLeftRight"},
            {"name": "E-Transfer", "icon": "Send"},
        ],
    },
    {
        "name": "Income",
        "transaction_type": "income",
        "icon": "CircleDollarSign",
        "subcategories": [
            {"name": "Cashback", "icon": "CreditCard"},
            {"name": "Interest Income", "icon": "PiggyBank"},
            {"name": "Salary Income", "icon": "TrendingUp"},
            {"name": "Other Income", "icon": "Banknote"},
        ],
    },
]
